apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpj-mdm-api-celery-worker
  labels:
    deployment: kpj-mdm-api-celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: kpj-mdm-api-celery-worker
  template:
    metadata:
      labels:
        pod: kpj-mdm-api-celery-worker
    spec:
      containers:
        - name: kpj-mdm-api-celery-worker
          image: syafiqpipe/kpj-mdm-api
          # celery -A kpj-mdm-api worker -l debug
          command: ['celery', '-A', 'core', 'worker', '-l', 'info']
          envFrom:
            - secretRef:
                name: kpj-mdm-api-secret            