apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpj-mdm-api-celery-beat
  labels:
    deployment: kpj-mdm-api-celery-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: kpj-mdm-api-celery-beat
  template:
    metadata:
      labels:
        pod: kpj-mdm-api-celery-beat
    spec:
      containers:
        - name: kpj-mdm-api-celery-beat
          image: syafiqpipe/kpj-mdm-api
          # celery -A kpj-mdm-api beat -l debug
          command: ['celery', '-A', 'core', 'beat', '-l', 'debug']
          envFrom:
            - secretRef:
                name: kpj-mdm-api-secret