apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpj-mdm-api-deployment
  labels:
    app: kpj-mdm-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kpj-mdm-api
  template:
    metadata:
      labels:
        app: kpj-mdm-api
    spec:
      containers:
      - name: kpj-mdm-api
        image: syafiqpipe/kpj-mdm-api:1.0.4 #boleh tambah version
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        envFrom:
          - secretRef:
              name: kpj-mdm-api-secret